#server
server:
  port: 84
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /
    
#spring datasource
spring:
  resources:
      #前端静态资源路径
    static-locations: classpath:/dist/ 
  datasource:
    url: jdbc:mysql:///enterprise?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/dist/
    #废弃前端文件路径
#    prefix: classpath:/templates/pages/
    suffix: .html
    #使用jdk代理aop
  aop:
    proxy-target-class: false    
    
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml
  
#log
logging:
  level:
    com.qxn: DEBUG
    
#spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
#spring async pool
async-thread-pool:
  corePoolSize: 5
  maxPoolSize: 5
  keepAliveSeconds: 600
  queueCapacity: 5
  
    