server:
  port: 8073
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/c2csystemdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    url: jdbc:mysql://192.168.89.1:3306/c2csystemdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.qxn.pojo
  mapper-locations: classpath:/mybatis.mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.qxn.mapper: debug

#dubbo配置
dubbo:
  scan:
    basePackages: com.qxn #包扫描
  application:
    name: provider-user #定义服务名称
  registry:
    address: zookeeper://192.168.89.129:2181?backup=192.168.89.129:2182,192.168.89.129:2183
  protocol:
    name: dubbo #dubbo节点保存的名称
    port: 20880 #dubbo rpc调用的端口信息